version: '3.9'


services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

#  web:
#    build:
#      dockerfile: Dockerfile
#      context: .
#      target: deploy
#    env_file:
#      - .env
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres



volumes:
  postgres:
